<?php
require 'Pessoa.class.php';
class PessoaFisica extends Pessoa{

    public $cpf;

    public function exibeDados()
    {
        parent::exibeDados(); // TODO: Change the autogenerated stub
        echo "<br> CPF: $this->cpf <br>";
    }
}

$fulano = new PessoaFisica();
$fulano->nome = 'Fulano';
$fulano->email = 'fulano@fulano.com';
$fulano->telefone = 9999999999;
$fulano->cpf = 99999999999999;

$fulano->exibeDados();

$fulano->addRendimento(1000);

echo "O valor do saldo é: ".$fulano->verRendimento();

